# Generated by Django 4.2.5 on 2023-09-05 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_title_alter_books_rental_rental_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_rental',
            name='book_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='books_rental',
            name='rental_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 5, 14, 58, 12, 956506, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='books_rental',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 12, 14, 58, 12, 956506, tzinfo=datetime.timezone.utc)),
        ),
    ]
