# Generated by Django 4.2.5 on 2023-09-06 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_rental_book_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books_rental',
            name='rental_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 6, 7, 37, 16, 167365, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='books_rental',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 13, 7, 37, 16, 167365, tzinfo=datetime.timezone.utc)),
        ),
    ]
