# Generated by Django 4.2.5 on 2023-09-06 07:49

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_like_alter_books_rental_rental_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books_rental',
            name='rental_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 6, 7, 49, 6, 853480, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='books_rental',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 13, 7, 49, 6, 853480, tzinfo=datetime.timezone.utc)),
        ),
    ]
