# Generated by Django 4.2.5 on 2023-09-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_created_alter_books_rental_rental_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_rental',
            name='rental_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='books_rental',
            name='return_date',
            field=models.DateField(),
        ),
    ]
