# Generated by Django 4.2.5 on 2023-09-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_books_rental_rental_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
